export const items = {
  fish: [
    "tench, Tinca tinca",
    "goldfish, Carassius auratus",
    "electric ray, crampfish, numbfish, torpedo",
    "barracouta, snoek",
    "rock beauty, Holocanthus tricolor",
    "anemone fish",
    "sturgeon",
    "gar, garfish, garpike, billfish, Lepisosteus osseus",
    "lionfish",
    "puffer, pufferfish, blowfish, globefish",
  ],
  shark: [
    "great white shark, white shark, man-eater, man-eating shark, " +
      "Carcharodon carcharias",
    "tiger shark, Galeocerdo cuvieri",
    "hammerhead, hammerhead shark",
  ],
  stingray: ["stingray"],
  chicken: ["cock", "hen"],
  ostrich: ["ostrich, Struthio camelus"],
  bird: [
    "brambling, Fringilla montifringilla",
    "goldfinch, Carduelis carduelis",
    "house finch, linnet, Carpodacus mexicanus",
    "junco, snowbird",
    "indigo bunting, indigo finch, indigo bird, Passerina cyanea",
    "robin, American robin, Turdus migratorius",
    "bulbul",
    "jay",
    "magpie",
    "chickadee",
    "water ouzel, dipper",
    "bald eagle, American eagle, Haliaeetus leucocephalus",
    "vulture",
    "great grey owl, great gray owl, Strix nebulosa",
    "black grouse",
    "ptarmigan",
    "ruffed grouse, partridge, Bonasa umbellus",
    "prairie chicken, prairie grouse, prairie fowl",
    "peacock",
    "quail",
    "partridge",
    "coucal",
    "bee eater",
    "hornbill",
    "hummingbird",
    "jacamar",
    "toucan",
    "drake",
    "red-breasted merganser, Mergus serrator",
    "goose",
    "black swan, Cygnus atratus",
    "white stork, Ciconia ciconia",
    "black stork, Ciconia nigra",
    "spoonbill",
    "flamingo",
    "little blue heron, Egretta caerulea",
    "American egret, great white heron, Egretta albus",
    "bittern",
    "crane",
    "limpkin, Aramus pictus",
    "European gallinule, Porphyrio porphyrio",
    "American coot, marsh hen, mud hen, water hen, Fulica americana",
    "bustard",
    "ruddy turnstone, Arenaria interpres",
    "red-backed sandpiper, dunlin, Erolia alpina",
    "redshank, Tringa totanus",
    "dowitcher",
    "oystercatcher, oyster catcher",
    "pelican",
    "albatross, mollymawk",
  ],
  kite: ["kite"],
  lizard: [
    "European fire salamander, Salamandra salamandra",
    "common newt, Triturus vulgaris",
    "eft",
    "spotted salamander, Ambystoma maculatum",
    "axolotl, mud puppy, Ambystoma mexicanum",
    "banded gecko",
    "common iguana, iguana, Iguana iguana",
    "American chameleon, anole, Anolis carolinensis",
    "whiptail, whiptail lizard",
    "agama",
    "frilled lizard, Chlamydosaurus kingi",
    "alligator lizard",
    "Gila monster, Heloderma suspectum",
    "green lizard, Lacerta viridis",
    "African chameleon, Chamaeleo chamaeleon",
  ],
  frog: [
    "bullfrog, Rana catesbeiana",
    "tree frog, tree-frog",
    "tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui",
  ],
  turtle: [
    "loggerhead, loggerhead turtle, Caretta caretta",
    "leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea",
    "mud turtle",
  ],
  crocodile: [
    "African crocodile, Nile crocodile, Crocodylus niloticus",
    "American alligator, Alligator mississipiensis",
  ],
  dinosaur: ["triceratops"],
  snake: [
    "thunder snake, worm snake, Carphophis amoenus",
    "ringneck snake, ring-necked snake, ring snake",
    "hognose snake, puff adder, sand viper",
    "green snake, grass snake",
    "king snake, kingsnake",
    "garter snake, grass snake",
    "water snake",
    "vine snake",
    "night snake, Hypsiglena torquata",
    "boa constrictor, Constrictor constrictor",
    "rock python, rock snake, Python sebae",
    "Indian cobra, Naja naja",
    "green mamba",
    "sea snake",
    "horned viper, cerastes, sand viper, horned asp, Cerastes cornutus",
    "diamondback, diamondback rattlesnake, Crotalus adamanteus",
    "sidewinder, horned rattlesnake, Crotalus cerastes",
    "eel",
  ],
  spider: [
    "harvestman, daddy longlegs, Phalangium opilio",
    "black and gold garden spider, Argiope aurantia",
    "barn spider, Araneus cavaticus",
    "garden spider, Aranea diademata",
    "black widow, Latrodectus mactans",
    "tarantula",
    "wolf spider, hunting spider",
  ],
  scorpion: ["scorpion"],
  insect: [
    "tick",
    "grasshopper, hopper",
    "cricket",
    "walking stick, walkingstick, stick insect",
    "cockroach, roach",
    "mantis, mantid",
    "cicada, cicala",
    "leafhopper",
  ],
  centipede: ["centipede"],
  parrot: [
    "African grey, African gray, Psittacus erithacus",
    "macaw",
    "sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita",
    "lorikeet",
  ],
  echidna: ["echidna, spiny anteater, anteater"],
  kangaroo: ["wallaby, brush kangaroo"],
  koala: [
    "koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus",
  ],
  wombat: ["wombat"],
  jellyfish: ["jelly fish"],
  coral: ["sea anemone, anemone", "brain coral"],
  worm: [
    "flatworm, platyhelminth",
    "nematode, nematode worm, roundworm",
    "slug",
    "sea slug, nudibranch",
    "sea cucumber, holothurian",
  ],
  snail: ["conch", "snail", "chambered nautilus, pearly nautilus, nautilus"],
  crab: [
    "Dungeness crab, Cancer magister",
    "rock crab, Cancer irroratus",
    "fiddler crab",
    "American lobster, Northern lobster, Maine lobster, Homarus americanus",
    "crayfish, crawfish, crawdad, crawdaddy",
    "hermit crab",
  ],
  penguin: ["king penguin, Aptenodytes patagonica"],
  whale: ["killer whale, killer, orca, grampus, sea wolf, Orcinus orca"],
  dog: [
    "Chihuahua",
    "Japanese spaniel",
    "Maltese dog, Maltese terrier, Maltese",
    "Pekinese, Pekingese, Peke",
    "Shih-Tzu",
    "Blenheim spaniel",
    "papillon",
    "toy terrier",
    "Rhodesian ridgeback",
    "Afghan hound, Afghan",
    "basset, basset hound",
    "beagle",
    "bloodhound, sleuthhound",
    "bluetick",
    "black-and-tan coonhound",
    "Walker hound, Walker foxhound",
    "English foxhound",
    "redbone",
    "borzoi, Russian wolfhound",
    "Irish wolfhound",
    "Italian greyhound",
    "whippet",
    "Ibizan hound, Ibizan Podenco",
    "Norwegian elkhound, elkhound",
    "otterhound, otter hound",
    "Saluki, gazelle hound",
    "Scottish deerhound, deerhound",
    "Weimaraner",
    "Staffordshire bullterrier, Staffordshire bull terrier",
    "Bedlington terrier",
    "Border terrier",
    "Kerry blue terrier",
    "Irish terrier",
    "Norfolk terrier",
    "Norwich terrier",
    "Yorkshire terrier",
    "wire-haired fox terrier",
    "Lakeland terrier",
    "Sealyham terrier, Sealyham",
    "Airedale, Airedale terrier",
    "cairn, cairn terrier",
    "Australian terrier",
    "Dandie Dinmont, Dandie Dinmont terrier",
    "Boston bull, Boston terrier",
    "miniature schnauzer",
    "giant schnauzer",
    "standard schnauzer",
    "Scotch terrier, Scottish terrier, Scottie",
    "Tibetan terrier, chrysanthemum dog",
    "silky terrier, Sydney silky",
    "soft-coated wheaten terrier",
    "West Highland white terrier",
    "Lhasa, Lhasa apso",
    "flat-coated retriever",
    "curly-coated retriever",
    "golden retriever",
    "Labrador retriever",
    "Chesapeake Bay retriever",
    "German short-haired pointer",
    "vizsla, Hungarian pointer",
    "English setter",
    "Irish setter, red setter",
    "Gordon setter",
    "Brittany spaniel",
    "clumber, clumber spaniel",
    "English springer, English springer spaniel",
    "Welsh springer spaniel",
    "cocker spaniel, English cocker spaniel, cocker",
    "Sussex spaniel",
    "Irish water spaniel",
    "kuvasz",
    "schipperke",
    "groenendael",
    "malinois",
    "briard",
    "kelpie",
    "komondor",
    "Old English sheepdog, bobtail",
    "Shetland sheepdog, Shetland sheep dog, Shetland",
    "collie",
    "Border collie",
    "Bouvier des Flandres, Bouviers des Flandres",
    "Rottweiler",
    "German shepherd, German shepherd dog, German police dog, alsatian",
    "Doberman, Doberman pinscher",
    "miniature pinscher",
    "Greater Swiss Mountain dog",
    "Bernese mountain dog",
    "Appenzeller",
    "EntleBucher",
    "boxer",
    "bull mastiff",
    "Tibetan mastiff",
    "French bulldog",
    "Great Dane",
    "Saint Bernard, St Bernard",
    "Eskimo dog, husky",
    "malamute, malemute, Alaskan malamute",
    "Siberian husky",
    "dalmatian, coach dog, carriage dog",
    "affenpinscher, monkey pinscher, monkey dog",
    "basenji",
    "pug, pug-dog",
    "Leonberg",
    "Newfoundland, Newfoundland dog",
    "Great Pyrenees",
    "Samoyed, Samoyede",
    "Pomeranian",
    "chow, chow chow",
    "keeshond",
    "Brabancon griffon",
    "Pembroke, Pembroke Welsh corgi",
    "Cardigan, Cardigan Welsh corgi",
    "toy poodle",
    "miniature poodle",
    "standard poodle",
    "Mexican hairless",
    "timber wolf, grey wolf, gray wolf, Canis lupus",
    "white wolf, Arctic wolf, Canis lupus tundrarum",
    "red wolf, maned wolf, Canis rufus, Canis niger",
    "coyote, prairie wolf, brush wolf, Canis latrans",
    "dingo, warrigal, warragal, Canis dingo",
    "dhole, Cuon alpinus",
    "African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus",
  ],
  hyena: ["hyena, hyaena"],
  fox: [
    "red fox, Vulpes vulpes",
    "kit fox, Vulpes macrotis",
    "Arctic fox, white fox, Alopex lagopus",
    "grey fox, gray fox, Urocyon cinereoargenteus",
  ],
  cat: [
    "tabby, tabby cat",
    "tiger cat",
    "Persian cat",
    "Siamese cat, Siamese",
    "Egyptian cat",
  ],
  leopard: [
    "lynx, catamount",
    "leopard, Panthera pardus",
    "snow leopard, ounce, Panthera uncia",
    "jaguar, panther, Panthera onca, Felis onca",
  ],
  lion: ["lion, king of beasts, Panthera leo"],
  tiger: ["tiger, Panthera tigris"],
  cheetah: ["cheetah, chetah, Acinonyx jubatus"],
  bear: [
    "brown bear, bruin, Ursus arctos",
    "ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus",
    "sloth bear, Melursus ursinus, Ursus ursinus",
  ],
  mouse: [
    "mongoose",
    "hamster",
    "marmot",
    "guinea pig, Cavia cobaya",
    "weasel",
    "mink",
    "polecat, fitch, foulmart, foumart, Mustela putorius",
    "black-footed ferret, ferret, Mustela nigripes",
    "badger",
  ],
  meerkat: ["meerkat, mierkat"],
  ladybug: ["ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle"],
  beetle: [
    "tiger beetle",
    "ground beetle, carabid beetle",
    "long-horned beetle, longicorn, longicorn beetle",
    "leaf beetle, chrysomelid",
    "dung beetle",
    "rhinoceros beetle",
    "weevil",
  ],
  fly: ["fly", "lacewing, lacewing fly", "damselfly"],
  bee: ["bee"],
  ant: ["ant, emmet, pismire"],
  butterfly: [
    "admiral",
    "ringlet, ringlet butterfly",
    "monarch, monarch butterfly, milkweed butterfly, Danaus plexippus",
    "cabbage butterfly",
    "sulphur butterfly, sulfur butterfly",
    "lycaenid, lycaenid butterfly",
  ],
  starfish: ["starfish, sea star"],
  rabbit: [
    "wood rabbit, cottontail, cottontail rabbit",
    "hare",
    "Angora, Angora rabbit",
  ],
  hedgehog: ["porcupine, hedgehog"],
  squirrel: ["fox squirrel, eastern fox squirrel, Sciurus niger"],
  zebra: ["zebra"],
  pig: [
    "hog, pig, grunter, squealer, Sus scrofa",
    "wild boar, boar, Sus scrofa",
    "warthog",
  ],
  hippopotamus: ["hippopotamus, hippo, river horse, Hippopotamus amphibius"],
  ox: [
    "ox",
    "water buffalo, water ox, Asiatic buffalo, Bubalus bubalis",
    "bison",
  ],
  sheep: ["ram, tup"],
  antelope: [
    "ibex, Capra ibex",
    "hartebeest",
    "impala, Aepyceros melampus",
    "gazelle",
  ],
  camel: ["Arabian camel, dromedary, Camelus dromedarius"],
  llama: ["llama"],
  otter: ["otter"],
  skunk: ["skunk, polecat, wood pussy"],
  armadillo: ["armadillo"],
  monkey: [
    "orangutan, orang, orangutang, Pongo pygmaeus",
    "gorilla, Gorilla gorilla",
    "chimpanzee, chimp, Pan troglodytes",
    "gibbon, Hylobates lar",
    "siamang, Hylobates syndactylus, Symphalangus syndactylus",
    "guenon, guenon monkey",
    "patas, hussar monkey, Erythrocebus patas",
    "baboon",
    "macaque",
    "langur",
    "colobus, colobus monkey",
    "proboscis monkey, Nasalis larvatus",
    "marmoset",
    "capuchin, ringtail, Cebus capucinus",
    "howler monkey, howler",
    "titi, titi monkey",
    "spider monkey, Ateles geoffroyi",
    "squirrel monkey, Saimiri sciureus",
    "Madagascar cat, ring-tailed lemur, Lemur catta",
  ],
  elephant: [
    "Indian elephant, Elephas maximus",
    "African elephant, Loxodonta africana",
  ],
  panda: [
    "lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens",
    "giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca",
  ],
  abacus: ["abacus"],
  gown: [
    "abaya",
    "academic gown, academic robe, judge's robe",
    "cloak",
    "gown",
    "poncho",
    "vestment",
  ],
  accordion: ["accordion, piano accordion, squeeze box"],
  guitar: ["acoustic guitar", "banjo", "electric guitar"],
  carrier: ["aircraft carrier, carrier, flattop, attack aircraft carrier"],
  airplane: ["airliner", "warplane, military plane"],
  airship: ["airship, dirigible"],
  altar: ["altar"],
  ambulance: ["ambulance"],
  clock: ["analog clock", "digital clock", "digital watch", "wall clock"],
  apiary: ["apiary, bee house"],
  apron: ["apron"],
  rifle: ["assault rifle, assault gun", "rifle"],
  backpack: ["backpack, back pack, knapsack, packsack, rucksack, haversack"],
  bakery: ["bakery, bakeshop, bakehouse"],
  balloon: ["balloon"],
  pen: [
    "ballpoint, ballpoint pen, ballpen, Biro",
    "fountain pen",
    "quill, quill pen",
  ],
  handrail: ["bannister, banister, balustrade, balusters, handrail"],
  barbell: ["barbell", "dumbbell"],
  chair: ["barber chair", "folding chair", "rocking chair, rocker"],
  barn: ["barn"],
  gauge: ["barometer", "odometer, hodometer, mileometer, milometer"],
  barrel: ["barrel, cask"],
  barrow: ["barrow, garden cart, lawn cart, wheelbarrow"],
  ball: [
    "baseball",
    "basketball",
    "croquet ball",
    "golf ball",
    "ping-pong ball",
    "rugby ball",
    "soccer ball",
    "tennis ball",
    "volleyball",
  ],
  flute: ["bassoon", "flute, transverse flute", "oboe, hautboy, hautbois"],
  hat: [
    "bathing cap, swimming cap",
    "bonnet, poke bonnet",
    "cowboy hat, ten-gallon hat",
    "shower cap",
    "sombrero",
  ],
  towel: ["bath towel", "paper towel"],
  bathtub: ["bathtub, bathing tub, bath, tub", "tub, vat"],
  lighthouse: ["beacon, lighthouse, beacon light, pharos"],
  beaker: ["beaker"],
  bearskin: ["bearskin, busby, shako"],
  bottle: [
    "beer bottle",
    "pill bottle",
    "pop bottle, soda bottle",
    "water bottle",
    "wine bottle",
  ],
  cup: [
    "beer glass",
    "cocktail shaker",
    "coffee mug",
    "goblet",
    "measuring cup",
    "water jug",
    "whiskey jug",
    "cup",
  ],
  bib: ["bib"],
  bicycle: ["bicycle-built-for-two, tandem bicycle, tandem"],
  bikini: ["bikini, two-piece"],
  binder: ["binder, ring-binder"],
  binoculars: ["binoculars, field glasses, opera glasses"],
  birdhouse: ["birdhouse"],
  bobsled: ["bobsled, bobsleigh, bob"],
  necktie: ["bolo tie, bolo, bola tie, bola", "bow tie, bow-tie, bowtie"],
  bookcase: ["bookcase"],
  bottlecap: ["bottlecap"],
  bow: ["bow"],
  bra: ["brassiere, bra, bandeau"],
  breastplate: ["breastplate, aegis, egis", "cuirass"],
  broom: ["broom"],
  bucket: ["bucket, pail"],
  buckle: ["buckle"],
  vest: ["bulletproof vest"],
  train: ["bullet train, bullet"],
  taxi: ["cab, hack, taxi, taxicab"],
  caldron: ["caldron, cauldron"],
  candle: ["candle, taper, wax light"],
  cannon: ["cannon"],
  boat: ["canoe", "catamaran", "gondola", "lifeboat", "speedboat", "trimaran"],
  sweater: ["cardigan", "sweatshirt"],
  carousel: ["carousel, carrousel, merry-go-round, roundabout, whirligig"],
  tools: ["carpenter's kit, tool kit"],
  carton: ["carton"],
  wheel: ["car wheel", "potter's wheel"],
  cassette: ["cassette", "cassette player"],
  castle: ["castle"],
  cello: ["cello, violoncello"],
  phone: [
    "cellular telephone, cellular phone, cellphone, cell, mobile phone",
    "dial telephone, dial phone",
  ],
  chain: ["chain", "chainlink fence"],
  chainsaw: ["chain saw, chainsaw"],
  chest: ["chest", "medicine chest, medicine cabinet"],
  bell: ["chime, bell, gong"],
  cabinet: ["china cabinet, china closet"],
  sock: ["Christmas stocking", "sock"],
  church: ["church, church building"],
  knife: [
    "cleaver, meat cleaver, chopper",
    "letter opener, paper knife, paperknife",
  ],
  coffeepot: ["coffeepot"],
  coil: ["coil, spiral, volute, whorl, helix"],
  lock: ["combination lock"],
  keyboard: ["computer keyboard, keypad", "typewriter keyboard"],
  ship: [
    "container ship, containership, container vessel",
    "liner, ocean liner",
    "pirate, pirate ship",
    "schooner",
  ],
  car: [
    "convertible",
    "jeep, landrover",
    "minivan",
    "Model T",
    "racer, race car, racing car",
    "sports car, sport car",
  ],
  corkscrew: ["corkscrew, bottle screw"],
  trumpet: ["cornet, horn, trumpet, trump", "French horn, horn"],
  shoe: ["cowboy boot", "Loafer", "running shoe"],
  cradle: ["cradle", "crib, cot"],
  helmet: ["crash helmet", "football helmet"],
  crate: ["crate"],
  pot: ["Crock Pot", "hot pot, hotpot"],
  desk: ["desk"],
  computer: ["desktop computer"],
  napkin: [
    "diaper, nappy, napkin",
    "dishrag, dishcloth",
    "handkerchief, hankie, hanky, hankey",
    "toilet tissue, toilet paper, bathroom tissue",
  ],
  table: ["dining table, board"],
  dishwasher: ["dishwasher, dish washer, dishwashing machine"],
  disk: ["disk brake, disc brake"],
  doormat: ["doormat, welcome mat"],
  drum: ["drum, membranophone, tympan"],
  stick: ["drumstick"],
  fan: ["electric fan, blower"],
  locomotive: [
    "electric locomotive",
    "steam locomotive",
    "streetcar, tram, tramcar, trolley, trolley car",
  ],
  envelope: ["envelope"],
  powder: ["face powder"],
  flagpole: ["flagpole, flagstaff", "pole", "totem pole"],
  forklift: ["forklift"],
  fountain: ["fountain"],
  frypan: ["frying pan, frypan, skillet", "wok"],
  coat: ["fur coat", "lab coat, laboratory coat", "trench coat"],
  truck: [
    "garbage truck, dustcart",
    "mobile home, manufactured home",
    "moving van",
    "pickup, pickup truck",
    "recreational vehicle, RV, R.V.",
    "tow truck, tow car, wrecker",
  ],
  gasmask: ["gasmask, respirator, gas helmet"],
  piano: ["grand piano, grand", "upright, upright piano"],
  greenhouse: ["greenhouse, nursery, glasshouse"],
  radiator: ["grille, radiator grille", "radiator"],
  guillotine: ["guillotine"],
  spray: ["hair spray"],
  hammer: ["hammer"],
  basket: ["hamper", "shopping basket"],
  laptop: [
    "hand-held computer, hand-held microcomputer",
    "laptop, laptop computer",
    "notebook, notebook computer",
  ],
  harmonica: ["harmonica, mouth organ, harp, mouth harp"],
  harp: ["harp"],
  hatchet: ["hatchet"],
  holster: ["holster"],
  honeycomb: ["honeycomb"],
  hook: ["hook, claw"],
  hourglass: ["hourglass"],
  iron: ["iron, smoothing iron"],
  denim: ["jean, blue jean, denim"],
  shirt: ["jersey, T-shirt, tee shirt"],
  puzzle: ["jigsaw puzzle"],
  kimono: ["kimono"],
  knot: ["knot"],
  spoon: ["ladle", "wooden spoon"],
  lamp: ["lampshade, lamp shade", "table lamp"],
  mower: ["lawn mower, mower"],
  lighter: ["lighter, light, igniter, ignitor"],
  limousine: ["limousine, limo"],
  lipstick: ["lipstick, lip rouge"],
  compass: ["magnetic compass"],
  bag: ["mailbag, postbag", "plastic bag"],
  mailbox: ["mailbox, letter box"],
  swimsuit: ["maillot", "maillot, tank suit"],
  xylophone: ["marimba, xylophone"],
  mask: ["mask", "oxygen mask", "ski mask"],
  matchstick: ["matchstick"],
  labyrinth: ["maze, labyrinth"],
  microphone: ["microphone, mike"],
  microwave: ["microwave, microwave oven"],
  uniform: ["military uniform"],
  bus: [
    "minibus",
    "school bus",
    "trolleybus, trolley coach, trackless trolley",
  ],
  skirt: ["miniskirt, mini", "overskirt"],
  missile: ["missile", "projectile, missile"],
  mitten: ["mitten"],
  bowl: ["mixing bowl", "soup bowl"],
  monitor: ["monitor", "screen, CRT screen", "television, television system"],
  bike: [
    "moped",
    "motor scooter, scooter",
    "mountain bike, all-terrain bike, off-roader",
  ],
  net: ["mosquito net"],
  tent: ["mountain tent"],
  mousetrap: ["mousetrap"],
  muzzle: ["muzzle"],
  nail: ["nail"],
  necklace: ["neck brace", "necklace"],
  potato: ["ocarina, sweet potato"],
  paddle: ["paddle, boat paddle"],
  padlock: ["padlock"],
  paintbrush: ["paintbrush"],
  parachute: ["parachute, chute"],
  bench: ["park bench"],
  perfume: ["perfume, essence"],
  pillow: ["pillow"],
  pinwheel: ["pinwheel"],
  plow: ["plow, plough"],
  plunger: ["plunger, plumber's helper"],
  camera: ["Polaroid camera, Polaroid Land camera", "reflex camera"],
  drill: ["power drill"],
  printer: ["printer"],
  projector: ["projector"],
  purse: ["purse"],
  racket: ["racket, racquet"],
  gun: ["revolver, six-gun, six-shooter"],
  eraser: ["rubber eraser, rubber, pencil eraser"],
  ruler: ["rule, ruler"],
  safe: ["safe"],
  pin: ["safety pin"],
  saltshaker: ["saltshaker, salt shaker"],
  sandal: ["sandal"],
  saxophone: ["sax, saxophone"],
  scale: ["scale, weighing machine"],
  scoreboard: ["scoreboard"],
  screw: ["screw"],
  screwdriver: ["screwdriver"],
  seatbelt: ["seat belt, seatbelt"],
  shield: ["shield, buckler"],
  shovel: ["shovel"],
  curtain: ["shower curtain"],
  ski: ["ski"],
  door: ["sliding door"],
  snorkel: ["snorkel"],
  snowmobile: ["snowmobile"],
  snowplow: ["snowplow, snowplough"],
  heater: ["space heater"],
  spatula: ["spatula"],
  cobweb: ["spider web, spider's web"],
  bridge: ["steel arch bridge", "suspension bridge"],
  stethoscope: ["stethoscope"],
  scarf: ["stole"],
  stopwatch: ["stopwatch, stop watch"],
  stove: ["stove"],
  strainer: ["strainer"],
  stretcher: ["stretcher"],
  submarine: ["submarine, pigboat, sub, U-boat"],
  suit: ["suit, suit of clothes"],
  sundial: ["sundial"],
  sunglasses: ["sunglass", "sunglasses, dark glasses, shades"],
  mop: ["swab, swob, mop"],
  pants: ["swimming trunks, bathing trunks"],
  swing: ["swing"],
  switch: ["switch, electric switch, electrical switch"],
  syringe: ["syringe"],
  tank: ["tank, army tank, armored combat vehicle, armoured combat vehicle"],
  teapot: ["teapot"],
  throne: ["throne"],
  toaster: ["toaster"],
  torch: ["torch"],
  tractor: ["tractor"],
  tripod: ["tripod"],
  umbrella: ["umbrella"],
  vacuum: ["vacuum, vacuum cleaner"],
  vase: ["vase"],
  vault: ["vault"],
  violin: ["violin, fiddle"],
  wallet: ["wallet, billfold, notecase, pocketbook"],
  wardrobe: ["wardrobe, closet, press"],
  whistle: ["whistle"],
  hair: ["wig"],
  icecream: ["ice cream, icecream"],
  bread: ["French loaf", "bagel, beigel", "pretzel"],
  burger: ["cheeseburger"],
  hotdog: ["hotdog, hot dog, red hot"],
  cabbage: ["head cabbage", "broccoli", "cauliflower"],
  cucumber: ["cucumber, cuke"],
  artichoke: ["artichoke, globe artichoke"],
  mushroom: ["mushroom"],
  strawberry: ["strawberry"],
  orange: ["orange"],
  lemon: ["lemon"],
  pineapple: ["pineapple, ananas"],
  banana: ["banana"],
  hay: ["hay"],
  pizza: ["pizza, pizza pie"],
  burrito: ["burrito"],
  volcano: ["volcano"],
  corn: ["corn"],
  acorn: ["acorn"],
};
